from reportlab.platypus import (
    SimpleDocTemplate,
    Paragraph,
    Spacer
)

from reportlab.lib.styles import getSampleStyleSheet
from reportlab.lib.enums import TA_CENTER


def create_pdf(
    file_path,
    meeting_title,
    meeting_date,
    language,
    summary_type,
    meeting_notes
):
    """
    Creates a professional PDF report
    containing AI-generated meeting notes.
    """

    document = SimpleDocTemplate(file_path)

    styles = getSampleStyleSheet()

    title_style = styles["Heading1"]
    title_style.alignment = TA_CENTER

    heading_style = styles["Heading2"]

    body_style = styles["BodyText"]

    story = []

    # Title
    story.append(
        Paragraph(
            "AI Meeting Notes Report",
            title_style
        )
    )

    story.append(
        Spacer(1, 20)
    )

    # Meeting Information
    story.append(
        Paragraph(
            f"<b>Meeting Title:</b> {meeting_title}",
            body_style
        )
    )

    story.append(
        Paragraph(
            f"<b>Meeting Date:</b> {meeting_date}",
            body_style
        )
    )

    story.append(
        Paragraph(
            f"<b>Language:</b> {language}",
            body_style
        )
    )

    story.append(
        Paragraph(
            f"<b>Summary Type:</b> {summary_type}",
            body_style
        )
    )

    story.append(
        Spacer(1, 20)
    )

    # Notes Heading
    story.append(
        Paragraph(
            "Meeting Notes",
            heading_style
        )
    )

    story.append(
        Spacer(1, 10)
    )

    # Meeting Notes
    for line in meeting_notes.split("\n"):

        story.append(
            Paragraph(
                line,
                body_style
            )
        )

    story.append(
        Spacer(1, 20)
    )

    story.append(
        Paragraph(
            "<b>Generated by AI Meeting Notes Generator</b>",
            body_style
        )
    )

    document.build(story)